# Form implementation generated from reading ui file '/Users/kevinab25/Development/vine_robot/MainController.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainController(object):
    def setupUi(self, MainController):
        MainController.setObjectName("MainController")
        MainController.resize(957, 593)
        self.centralwidget = QtWidgets.QWidget(MainController)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 130, 100, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 200, 100, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 200, 100, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 280, 100, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 110, 100, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 110, 100, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        MainController.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 22))
        self.menubar.setObjectName("menubar")
        MainController.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainController)
        self.statusbar.setObjectName("statusbar")
        MainController.setStatusBar(self.statusbar)

        self.retranslateUi(MainController)
        QtCore.QMetaObject.connectSlotsByName(MainController)

    def retranslateUi(self, MainController):
        _translate = QtCore.QCoreApplication.translate
        MainController.setWindowTitle(_translate("MainController", "MainWindow"))
        self.pushButton.setText(_translate("MainController", "PushButton"))
        self.pushButton_2.setText(_translate("MainController", "PushButton"))
        self.pushButton_3.setText(_translate("MainController", "PushButton"))
        self.pushButton_4.setText(_translate("MainController", "PushButton"))
        self.pushButton_5.setText(_translate("MainController", "PushButton"))
        self.pushButton_6.setText(_translate("MainController", "PushButton"))
